#---
#apiVersion: backstage.io/v1alpha1
#kind: User
#metadata:
#  name: josef
#spec:
#  profile:
#    displayName: Josef Auer
#    email: josef.auer@example.com
#    picture: https://example.com/staff/jenny-with-party-hat.jpeg
#  memberOf: [core-team, employees]
#---
#apiVersion: backstage.io/v1alpha1
#kind: Domain
#metadata:
#  name: users
#  description: Everything about recipes
#spec:
#  owner: core-team
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: recipe-crud
  description: Create, Read Update Delete Recipes
spec:
  owner: baby-girls
  domain: recipes
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: recipe-ingestion
  description: Storing a recipe
spec:
  type: service
  lifecycle: production
  owner: core-team
  system: recipe-crud
  dependsOn:
    - resource:default/recipe-db
  providesApis:
    - recipe-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: recipe-site
  description: The website we show our customers
  links:
    - url: https://auer.biz
      title: The main site
      icon: dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - react
    - yarn
    - jest
spec:
  type: website
  lifecycle: production
  owner: core-team
  system: recipe-crud
  consumesApis:
    - recipe-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: recipe-search
  description: Searching for a recipe
  tags:
    - typescript
    - jest
    - behave
spec:
  type: service
  lifecycle: test
  owner: core-team
  system: recipe-crud
  dependsOn:
    - resource:default/recipe-db
    - resource:default/recipe-search-bucket
  providesApis:
    - recipe-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: recipe-recommendation
  description: Recommending a recipe
  tags:
    - golang
    - acceptancetest
    - nofu
spec:
  type: service
  lifecycle: production
  owner: core-team
  system: recipe-crud
  dependsOn:
    - resource:default/recipe-db
  providesApis:
    - recipe-api
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: recipe-db
  description: Stores all recipes
  links:
    - url: https://aurora.aws.login.something
      title: Aurora Login
      icon: database
  tags:
    - aurora
    - postgress
    - somethingelse
spec:
  type: database
  owner: core-team
  system: infra
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: recipe-search-bucket
  description: Search Index for Recipes
spec:
  type: database
  owner: core-team
  system: infra
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: recipe-api
  description: Retrieve recipe details
spec:
  type: openapi
  lifecycle: production
  owner: api-team
  system: apis
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists

#apiVersion: backstage.io/v1alpha1
#kind: Domain
#metadata:
#  name: recipes
#  description: Everything about recipes
#spec:
#  owner: core-team
